services:
  api:
    volumes:
      - .:/app
    ports:
      - "7815:8000"
    environment:
      - ENV=development
    command: sh -c "uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - "7811:3000"