services:
  db:
    image: postgres:16.4-alpine
    container_name: librion-db
    restart: always
    env_file:
      - .env
    ports:
      - "5678:5432"
    volumes:
      - librion-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: librion-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "7815:8000"
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn api.app:app --host 0.0.0.0 --port 8000
      "

  frontend:
    build:
      context: ./frontend
      target: pro
    container_name: librion-frontend
    depends_on:
      - api
    ports:
      - "7811:3000"
